#!/usr/bin/env python3
"""Write deskew debug PDFs next to a cleaned/deskewed scan.

By default writes only ``{stem}_projected_boxes.pdf`` (scaffold regions in 4-up space
projected onto the scan). Optional ``--reflines-overlay`` also writes
``{stem}_reflines_overlay.pdf`` (normally not generated by the pipeline).

The vector exam overlay (``*_scaffold_boxes.pdf``) is produced by
:func:`pipeline.scaffold.build_scaffold` / ``scripts/visualize_scaffold_boxes.py`` — not here.

Examples::

    python scripts/visualize_scan_overlays.py "Space Physics Unit Test"
    python scripts/visualize_scan_overlays.py "Space Physics Unit Test" \\
        --scan "Space Physics Unit Test/cleaned_trial_300dpi.pdf"
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from pipeline.exam_paths import exam_artifact_dir
from pipeline.scan_overlays import (
    write_projected_scaffold_debug_pdf,
    write_reflines_debug_pdf,
    write_scan_debug_pdfs_after_deskew,
)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument(
        "folder",
        type=Path,
        nargs="?",
        default=Path("."),
        help="Exam folder (scaffold cache + optional raw exam 4up)",
    )
    ap.add_argument(
        "--scan",
        type=Path,
        default=None,
        help="Deskewed raster PDF (default: output/<stem>/cleaned_scan.pdf, else exam folder)",
    )
    ap.add_argument(
        "--dpi",
        type=int,
        default=300,
        help="Rasterisation DPI of the scan PDF (default: 300)",
    )
    ap.add_argument(
        "--reflines-overlay",
        action="store_true",
        help="Also write the reflines debug PDF (not generated by grade.py by default)",
    )
    ap.add_argument(
        "--reflines-only",
        action="store_true",
        help="Only write the reflines overlay PDF",
    )
    ap.add_argument(
        "--projected-only",
        action="store_true",
        help="Only write the projected scaffold overlay PDF",
    )
    ap.add_argument(
        "--force-projected",
        action="store_true",
        help="Draw projected boxes even if scaffold exam PDF is not the 4-up file",
    )
    args = ap.parse_args()

    folder = args.folder.resolve()
    if args.scan:
        scan = args.scan.resolve()
    else:
        art = exam_artifact_dir(folder) / "cleaned_scan.pdf"
        leg = folder / "cleaned_scan.pdf"
        scan = art if art.is_file() else leg
    if not scan.is_file():
        print(f"Missing scan PDF: {scan}", file=sys.stderr)
        sys.exit(1)

    rfl = args.reflines_only and not args.projected_only
    prj = args.projected_only and not args.reflines_only
    if rfl:
        write_reflines_debug_pdf(scan, args.dpi)
    elif prj:
        write_projected_scaffold_debug_pdf(
            folder, scan, args.dpi, force_layout_mismatch=args.force_projected
        )
    else:
        write_scan_debug_pdfs_after_deskew(
            folder,
            scan,
            args.dpi,
            force_projected_mismatch=args.force_projected,
            write_reflines=args.reflines_overlay,
        )


if __name__ == "__main__":
    main()
